Improve error handling in my-canvas-rooms-api.
KTH/kpm pull request #113
Opened 2023-01-27 14:22 UTC by kaj

Is this a good way handle errors that should not be status 500 (and does not need to be logged as error) ?

2023-01-30 12:45 UTC, jhsware requested changes

2023-01-30 12:45 UTC, jhsware commented on apis/my-canvas-rooms-api/src/api.ts
> +}
There is a specific error class called `EndpointError` that would be more appropriate here than MutedOperationalError. The idea is that an EndpointError is used when:
- the consumer should handle this error specifically in the area of code calling this endpoint
- the type string should be documented through the passed ErrType generic (ref APIAuthErrType in kpm-backend-interface/src/index.ts) in an interface.ts file or package
- the type should be of the PascalCase form

2023-01-30 12:45 UTC, jhsware commented on apis/my-canvas-rooms-api/src/canvasApi.ts
> +class AuthTokenMissing extends MutedOperationalError<String> {
There is a specific `AuthError` that would be more appropriate than MutedOperationalError. The ErrType generic should also be documented in interface.ts as above.

2023-02-14 15:43 UTC, kaj reviewed
👍🏻 Looks ok to me.  And I believe the issues you had earlier was fixed by your commit?  I have rebased, so this should be mergeable now?

(I can't submit an approving review since the original changes in the PR was from me, but I approve your changes.)

2023-02-15 08:10 UTC, jhsware approved these changes
LGTM

Note: jag tror jag ska kika igenom våra Exceptions igen. Jag gillar idén att man inte kan välja "fel" err type genom att subklassa EndpointError per projekt, men frågan är om man det är overkill att ha specifika Exceptions för varje case. Jag pingar dig för diskussion när jag kikar på det.

2023-02-15 12:38 UTC, merged