Hide Studies / Teaching / Programmes if empty
KTH/kpm pull request #115
Opened 2023-01-31 14:47 UTC by jhsware

We are checking each group that the user belongs to to determine if the menu items should be shown:

studies: curr.startsWith("ladok2.kurser")
programmes: curr.startsWith("ladok2.program")
teaching: curr.startsWith("edu.courses")

2023-01-31 15:10 UTC, kaj commented
Jag är skeptisk till att ha ett sånt här villkor på program, eftersom de grupptillhörigheterna bara gäller studenter.  Alla de anställda som på något sätt jobbar med programen har "lagt tilll" dem manuellt i social.  Så man kanske skulle fråga social om användaren har valt några program i stället?  Eller bara alltid visa programmenyn.

(Mer review kommer när jag hunnit titta på själva koden också, men det blir nog i morgon.)

2023-01-31 15:14 UTC, jhsware commented
Bra inspel! Jag kanske blev lite övertaggad eftersom jag upptäckte att informationen fanns tillgänglig.

2023-02-01 08:07 UTC, kaj requested changes
Looks good, apart from the thing about programs.  I also have some nitpicks / questions, consider them optional!

2023-02-01 08:07 UTC, kaj commented on kpm/kpm-frontend/src/routes.tsx
>  };
Varför finns både den här typen och `TCreateRouterProps`?   De borde väl vara samma jämt, och då borde vi kunna använda samma typ?

2023-02-01 09:05 UTC, jhsware commented on kpm/kpm-backend/src/auth.ts
> +  );
WILL FIX!

2023-02-01 09:05 UTC, jhsware commented on kpm/kpm-backend-interface/src/index.ts
> +  hasLadokProgrammes?: boolean;
WILL FIX!

2023-02-01 09:12 UTC, jhsware commented on kpm/kpm-frontend/src/app.tsx
>    | undefined;
Egentligen tror jag att de ska vara separata eftersom sessionsanvändaren och användarobjektet i frontend har lite olika syften. Framöver kommer de nog divergera och jag var inne på att kalla propsen `hasStudiesMenu` etc. men valde det här för att det var lättare att läsa PR:en. Om du inte känner väldigt starkt för det så låter jag det vara som det är.

2023-02-01 09:19 UTC, jhsware commented on kpm/kpm-frontend/src/routes.tsx
>  };
Det finns ställen där getRoutes anropas utan att skicka några props och då behöver man sätta defaults på det här sättet AFAIK. Typningen sätter inte defaults.

MEN, jag kan flytta typen TCreateRouterProps till getRoutes så att det blir tydligare att de hör ihop. WILL FIX

2023-02-01 09:23 UTC, jhsware commented on kpm/kpm-backend/src/auth.ts
> +  );
Fixed in 48161579

2023-02-01 09:28 UTC, jhsware commented on kpm/kpm-backend-interface/src/index.ts
> +  hasLadokProgrammes?: boolean;
Fixed in 7e011a08b2

2023-02-01 09:31 UTC, jhsware commented on kpm/kpm-frontend/src/routes.tsx
>  };
Fixed in 588fc4f55

2023-02-01 09:49 UTC, kaj commented on kpm/kpm-frontend/src/app.tsx
>    | undefined;
Jag tycker nog ändå att _användarobjektet_ på frontendsessionen ska vara användarobjektet vi får från servern rakt av.  Sen kan det finnas annat data också i frontendsessionen.  Men det är ju som sagt egentligen orelaterad, så vi kan låta det vila ett tag och diskutera mer längre fram.

2023-02-01 09:59 UTC, kaj commented on kpm/kpm-frontend/src/Menu.tsx
> +export function Menu({ hasStudies, hasTeaching, hasProgramme }: any) {
här blev en `hasProgramme` kvar.  Den varken används eller sätts väl, så den bör nog plockas bort.

2023-02-01 10:22 UTC, jhsware commented on kpm/kpm-frontend/src/Menu.tsx
> +export function Menu({ hasStudies, hasTeaching, hasProgramme }: any) {
Fixed in 3ebc6473

2023-02-01 10:24 UTC, jhsware commented on kpm/kpm-frontend/src/app.tsx
>    | undefined;
Hmmmm jag håller nog faktiskt med dig. Jag flyttar typen till kpm-backend-interface p.g.a. som du säger, objektet skapas av backend även om det inte nödvändigtvis är exakt samma som sessionanvändaren.

WILL FIX

2023-02-01 10:50 UTC, kaj approved these changes
Looks all good now!

2023-02-01 14:12 UTC, merged