Kopps cache
KTH/kpm pull request #129
Opened 2023-02-15 13:45 UTC by jhsware

We now support a Redis cache for TKoppsCourseInfo to reduce calls to KOPPS.

- use Redis as cache for TKoppsCourseInfo
- use database 1 for cache and 0 for session
- clearly provide a legacy redis client for session (connect-redis)
- use NodeCache as fallback if Redis isn't available
- cache can easily be used for other data provided no key collisions

2023-02-15 15:04 UTC, kaj requested changes
Det mesta ser bra ut, jag har några undringar och några synpunkter ...

2023-02-15 15:10 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +export async function __CACHED_VALUE__<T extends TCacheable>(
Det fula namnet är mitt sätt att få det att sticka ut i koden. Hade helst implementerat som decorator, men det betraktas fortf. experimentellt i JS/TS. Det är alltså vid användning jag vill att det ska sticka ut. Men känns det som en tagg i sidan så får jag ofc ge med mig :D

Gillar idén! Men då borde man nästan bryta ut det till ett eget paket som vi kan dela mellan alla API:er. Jag kikar på att göra ändringen i första steget. Då kan man även lägga in TTL redan där.

2023-02-15 15:11 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +  const cachedValue = _getCachedValue<T>(key);
Hjärnsläpp! Jag ska ta och skriva tester...

2023-02-15 15:13 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +const redisClient = hasRedis ? getRedisClient(REDIS_DB_NAMES.KOPPS) : null;
Agree!

2023-02-15 15:14 UTC, jhsware commented on kpm/kpm-backend/src/redisClient.ts
> +  // Return the v4 node-redis client
Will fix

2023-02-15 15:21 UTC, jhsware commented on kpm/kpm-backend/src/redisClient.ts
> +  // Return the v4 node-redis client
Fixed in 24a57165f8

2023-02-15 15:21 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +const redisClient = hasRedis ? getRedisClient(REDIS_DB_NAMES.KOPPS) : null;
Fixed in d7dbf22095

2023-02-15 15:22 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +  if (newValue) _setCachedValue(key, newValue, ttlSecs);
Fixed in cb791641dd

2023-02-15 15:22 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +  const cachedValue = _getCachedValue<T>(key);
Fixed in cb791641dd

2023-02-16 09:51 UTC, kaj reviewed
Some more questions here ...

2023-02-16 09:51 UTC, kaj commented on kpm/kpm-backend/src/api/commonCache.ts
> +      // TODO: Should we throw an error instead?
If we want to provide commonCache as a package for others to use, we should probably just not catch the error, letting it propagate to the user.

If just for our own use case, I think we should log the error (at least as a warning, maybe as an error) in the catch.

2023-02-16 09:51 UTC, kaj commented on kpm/kpm-backend/src/api/common.ts
>        .then((r) => r.body);
Should we add a status code check here?  I don't think got throws an error on bad status code by default?

2023-02-16 09:51 UTC, kaj commented on kpm/kpm-backend/src/api/commonCache.ts
> +export class StringKeyCache<T extends TCacheable> {
I know I asked for a method, but now that I see it, and it has only private properties, a constructor and one single public method, maybe it should be replaced with a function (the constructor) returning a function (the method)?

2023-02-16 09:51 UTC, kaj commented on kpm/kpm-backend/src/api/commonCache.ts
> +  async cached(key: string): Promise<T | null | undefined> {
Should we really have both `null` and `undefined` in the return type?  If so, we should at least define the intended semantic difference.  If it's just that redis and nodecache uses different return values for "not found", we should unify that.

2023-02-17 10:24 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +      // TODO: Should we throw an error instead?
Fixed in 27ae41626

2023-02-17 10:29 UTC, jhsware commented on kpm/kpm-backend/src/api/common.ts
>        .then((r) => r.body);
Fixed in 1b2b63ca

2023-02-17 10:29 UTC, jhsware commented on kpm/kpm-backend/src/api/commonCache.ts
> +export class StringKeyCache<T extends TCacheable> {
Fixed in 4727279

2023-02-17 11:08 UTC, kaj approved these changes

2023-02-17 11:10 UTC, merged