Use acceppt-language.
KTH/kpm pull request #141
Opened 2023-03-01 11:10 UTC by kaj

Set accept-language on all backend requests in frontent, and propagate that header to any requests to social in the backend.

This fixes the translations for service links.

2023-03-01 11:43 UTC, jhsware requested changes
Do we need to look at KOPPS-calls too?

2023-03-01 11:43 UTC, jhsware commented on kpm/kpm-backend/src/session.ts
> +      ).catch(socialErr);
Is this endpoint language aware? Or are you passing lang for consistency?

2023-03-01 11:44 UTC, kaj commented on kpm/kpm-backend/src/session.ts
> +      ).catch(socialErr);
Just for consistency.  Currently, that endpoint only returns an object-wrapped json number.

2023-03-01 11:47 UTC, kaj commented
The kopps-dependant things we cache are independent of language (contains both languages), and I think we should keep it that way.  So no, I don't think we should change our kopps calls. But possibly our backend calls (which use those cached values) ?

2023-03-01 11:48 UTC, kaj commented on kpm/kpm-backend/src/session.ts
> +      ).catch(socialErr);
(I made the argument required, to avoid missing it anywhere it might be needed).

2023-03-02 12:30 UTC, kaj commented
Den kopps-endpoint vi använder i nuläget (`${KOPPS_API}/course/${course_code}/courseroundterms`) ger språkobjekt {sv: ..., en: ...}, så det är såna vi cachar.  Så inga problem där.  Vi skulle ju kunna tolka de objekten i kpm-backend och bara skicka rätt språk till kpm-frontend, men jag tycker nog att det kan vara en separat fråga till någon annan gång ...

2023-03-02 12:43 UTC, jhsware commented
LGTM

2023-03-02 12:43 UTC, jhsware approved these changes
LGTM

2023-03-02 12:49 UTC, merged