Use kth-style colors
KTH/kpm pull request #148
Opened 2023-03-07 13:32 UTC by kaj

Use kth-style sass variables in stylesVars.scss, to get proper kth-style colors and document where our colours come from.

2023-03-07 13:34 UTC, kaj commented
Note: It seems the prettier github action is out of date and don't really handle scss properly.  It works fine with my local prettier.

2023-03-08 07:33 UTC, jhsware requested changes
The core concept is outstanding. I have a question about a name change.

2023-03-08 07:33 UTC, jhsware commented on kpm/kpm-frontend/src/app.scss
> +    color: var(--kpmPaneTextSoft);
Is there a reason for the name change? To me "muted" has more appropriate meaning than "soft".

2023-03-08 08:24 UTC, kaj commented on kpm/kpm-frontend/src/app.scss
> +    color: var(--kpmPaneTextSoft);
It's not a naming change, it's a merge.  There was both a "muted" and a "soft" variant, and I think we should only have one kind of "text with less contrast".  As the gray level is closer to the one that was called soft i kept that name (I can change that if you think muted is the better name, but it won't make the diff smaler).

2023-03-08 09:07 UTC, jhsware commented on kpm/kpm-frontend/src/app.scss
> +    color: var(--kpmPaneTextSoft);
Oh, yeah I realise I used it for different things, but that relates to our previous discussion where muted might have been a bit too light. The merge was a great idea! Personally I prefer "muted" over "soft", this is influenced by Bootstrap using `.text-muted` as a class. If you disagree, perhaps you could ask Carlos to chime in.

2023-03-08 09:11 UTC, kaj commented on kpm/kpm-frontend/src/app.scss
> +    color: var(--kpmPaneTextSoft);
I feel strongly about the level of contrast, but don't really hava an opinion about the name, so I'll change it!  :-)

2023-03-08 09:22 UTC, jhsware approved these changes
LGTM

2023-03-08 09:22 UTC, merged