Filter out cancelled courses.
KTH/kpm pull request #150
Opened 2023-03-08 14:28 UTC by kaj

Add filtering for "Established" (not cancelled) or "All courses" in teaching.  This uses a new field, `state`, in the kopps API.  DO NOT MERGE until that field exists in production kopps.

Also make `KOPPS_API` configurable, so ref environment can be used for testing.

2023-03-08 14:49 UTC, kaj commented
Will change: I should probably send the actual `state` to the frontend instead of the `established` boolean value.  State can be `ESTABLISHED` or `CANCELLED`, but also `DEACTIVATED`.  For the actual filtering, I still think the default view should be `ESTABLISHED` only and the the other view should be All courses, but when viewing all courses, there is a note on cancelled courses, and that should be different for `DEACTIVATED` and `CANCELLED` courses to avoid confusion.

2023-03-08 15:05 UTC, jhsware requested changes
Looks very nice. Some points to discuss.

2023-03-08 15:05 UTC, jhsware commented on kpm/kpm-frontend/src/panes/teaching.tsx
> +        >
I can't remember if I tried using "all" as default on row 48. I must admit that `{filter || "all"}` is a bit weird.

2023-03-08 15:33 UTC, kaj commented on kpm/kpm-backend-interface/src/index.ts
> +  established: boolean;
I will change this to a `state` string, as I mentioned in comment.

2023-03-08 15:39 UTC, kaj commented on kpm/kpm-backend/src/api/teaching.ts
>          rooms: rooms ? rooms?.[course_code] || [] : null,
The definition of a course at KTH as I see it is "something that has a course code and can be looked up in kopps".  Other stuff (like the "Canvas@KTH" canvas room) is just administrative fluff and not part of neither studies or education.  😎

2023-03-08 15:51 UTC, kaj commented on kpm/kpm-frontend/src/panes/teaching.tsx
> +        >
That seems to be required by react, as the state one gets from `useState<T>` is not `T` but `T | undefined`.

What I think is a bit strange here is that everything is set on the FilterOptions rather than on the Filter.  If I could design the api for the filter tag, the call would look like this:

```ts
      <TabFilter<TFilter> selected={filter} onSelect={setFilter}>
        <FilterOption value="established">{i18n("established")}</FilterOption>
        <FilterOption value="all">{i18n("all_courses")}</FilterOption>
      </TabFilter>
```

2023-03-09 16:18 UTC, jhsware approved these changes
LGTM

2023-03-13 11:15 UTC, kaj commented
Hm.  Det här är ju en liten men väsentlig ändring i det koppsdata vi cachar.  Borde vi ändra `REDIS_DB_NAMES.KOPSS` till 2?  Ja, det borde vi nog?

2023-03-13 16:57 UTC, jhsware approved these changes
LGTM

2023-03-14 08:38 UTC, merged