Lang
KTH/kpm pull request #152
Opened 2023-03-14 16:02 UTC by kaj

2023-03-14 16:06 UTC, jhsware requested changes
Added some todos for good measure.

2023-03-14 16:06 UTC, jhsware commented on kpm/kpm-frontend/src/panes/profile.tsx
> +    // FIXME TODO: Handle the error!
Needs fixing, check set star.

2023-03-14 16:06 UTC, jhsware commented on kpm/kpm-frontend/src/panes/profile.tsx
> +    location.reload();
Should we use .replace() instead? https://developer.mozilla.org/en-US/docs/Web/API/Location/replace

2023-03-14 16:14 UTC, kaj commented on kpm/kpm-frontend/src/panes/profile.tsx
> +    location.reload();
Huh?  `.reload()` ger oss rätt url automagiskt, med `.replace(...)` måste vi hitta på en bra url också?

2023-03-15 10:15 UTC, jhsware approved these changes
LGTM

2023-03-15 10:17 UTC, jhsware requested changes
TODO: Update kpm-backend-interface
TODO: Add icon to language button

2023-03-15 11:30 UTC, kaj reviewed
Verkar väl rimligt nu?

2023-03-16 12:00 UTC, jhsware approved these changes
LGTM

2023-03-16 12:01 UTC, merged