implemented basic error handling
KTH/kpm pull request #17
Opened 2021-01-27 21:23 UTC by miyamoto-san

2021-01-29 11:11 UTC, kaj requested changes
Two things I think are rebase mistakes and one question about the actual error handling:

2021-01-29 11:11 UTC, kaj commented on server/panels/router.js
> -}
This function, and the calls to it, are still needed.  Or should those headers be set in some other way?

2021-01-29 11:11 UTC, kaj commented on server/server.js
> +    const search = await fetchBlock("search");
This also seems like a rebase error, as this reverts the caching PR by @exacs that was previously merged.

2021-01-29 11:11 UTC, kaj commented on server/login-router.js
> +    return res.status(400).send("");
How is any unexpected exception caught in the handler functions a request error, while similarly unexpected exceptions caught in the catchAll are server errors?

2021-02-02 09:22 UTC, exacs commented on server/login-router.js
> +    return res.status(400).send("");
Agree here. I think unexpected exceptions should not be handled in routes but in the `catchAll`

2021-02-02 09:38 UTC, exacs commented on server/panels/router.js
> -module.exports = panelsRouter;
This was move down. I don't have any opinions on that :)

2021-02-02 09:56 UTC, kaj approved these changes
Much smaller fixes now.  :-)  Seems ok to me from reading the code.

2021-02-02 11:27 UTC, merged