Sort services in columns.
KTH/kpm pull request #192
Opened 2023-06-01 12:59 UTC by kaj

The main selected services list is two columns, not a bunch of rows, so "Annual ..." comes below "Administrate", not beside.  Also a bunch of cleanup of the main layout of the services panel (less calc, fewer properties, let the flex handling in the browser do the math).

https://trello.com/c/n0GW8mHA

2023-06-01 13:31 UTC, jhsware commented on kpm/kpm-frontend/src/panes/services.scss
> +      column-width: 17em;
The value feels picked at random. Would be great with a comment OR using a calculation from a variable that is used somewhere related.

2023-06-01 13:32 UTC, jhsware commented on kpm/kpm-frontend/src/panes/services.scss
> +    flex: 13em 1;
This value also feels random. See other note.

2023-06-01 13:32 UTC, jhsware requested changes
The result looks good, but I have some comments regarding understandability.

2023-06-01 14:02 UTC, kaj commented on kpm/kpm-frontend/src/panes/services.scss
> +      column-width: 17em;
It is picked by trying different values and selecting one that looks good.  Not sure what to write in a comment about that, other than something like "this seems fine", which don't add much value ...

2023-06-01 14:02 UTC, kaj commented on kpm/kpm-frontend/src/panes/services.scss
> +    flex: 13em 1;
Same.  :-)

2023-06-02 10:34 UTC, jhsware approved these changes
LGTM

2023-06-02 10:34 UTC, jhsware approved these changes
LGTM

2023-06-02 10:36 UTC, merged