Program rooms improved(?)
KTH/kpm pull request #199
Opened 2023-07-20 10:38 UTC by kaj

2023-07-28 09:36 UTC, kaj reviewed
I wrote some motivation for most of my changes as a review here rather than on the original PR.

2023-07-28 09:36 UTC, kaj commented on apis/my-canvas-rooms-api/src/interface.ts
> +  programRooms?: Record<string, Link>;
Don't allow _both_ `undefined` and `null` value for the response fields.

2023-07-28 09:36 UTC, kaj commented on apis/my-canvas-rooms-api/src/interface.ts
> +  otherRooms?: Link[];
... and add `otherRooms` as a separate field for the fallback rooms, rather than treating them as course rooms for an unknown course.

2023-07-28 09:36 UTC, kaj commented on kpm/kpm-frontend/src/panes/programme.tsx
> +      </p>
Make the name of the program room the link to the program room rather than putting the most important thing in a little link to the right.   I think this is so much of a UX benefit that it is worth a little inconsistency as to the course rooms (as there may be more than one room for each course but only one for each program, there will be some inconsistency anyway).

2023-07-28 09:36 UTC, kaj commented on kpm/kpm-frontend/src/panes/programme.tsx
>          {i18n("Syllabus")}
Maybe repeat the program code here (e.g. "CDATE syllabus") to avoid having a bunch of same-word links?  On the other hand, many students will have only one syllabus anyway.

2023-08-07 11:23 UTC, jhsware requested changes

2023-08-07 11:23 UTC, jhsware commented on apis/my-canvas-rooms-api/src/interface.ts
> +  programRooms?: Record<string, Link>;
Lets discuss this.

2023-08-07 11:23 UTC, jhsware commented on apis/my-canvas-rooms-api/src/interface.ts
> +  otherRooms?: Link[];
Great idea!

2023-08-07 11:23 UTC, jhsware commented on kpm/kpm-frontend/src/panes/programme.tsx
> +      </p>
I agree that Clickable titles are preferable, but perhaps Carlos should way in on this change. @exacs

2023-08-07 11:23 UTC, jhsware commented on kpm/kpm-frontend/src/panes/programme.tsx
>          {i18n("Syllabus")}
I believe the idea is to be clear about where the link takes the user. A bit of repetition is okay IMO. As you noted, most users won't belong to a huge number of programs and they probably won't use this menu pane frequently enough to remember where the links take you. Keeping it as "Syllabus" for now is reasonable.

2023-08-07 14:45 UTC, jhsware approved these changes
LGTM

2023-08-07 14:47 UTC, merged