Make validators happy
KTH/kpm pull request #220
Opened 2024-01-09 12:16 UTC by kaj

Validators and Pär Landberg complained about mismatching types for some uses of the `--kpmPad` css variable.  Add a default of 1em (which is a sane if large default, but should never actually be used, as the variable have a global value).

2024-01-09 12:19 UTC, jhsware requested changes

2024-01-09 12:19 UTC, jhsware commented on kpm/kpm-frontend/src/Menu.scss
> +  $fullMenuHeight: calc(1.5em + 2 * var(--kpmPad, 1em));
--kpmPad är satt till `.5rem` i projektet vad jag kan se

2024-01-09 13:14 UTC, kaj commented on kpm/kpm-frontend/src/Menu.scss
> +  $fullMenuHeight: calc(1.5em + 2 * var(--kpmPad, 1em));
Om jag hade brytt mig om att sätta "rätt" värde så hade jag inte använt en css-variabel med ett defaultvärde, utan bara värdet rakt av (kanske via en sass-variabel).  Jag valde `1em` för att det är det enklaste och kortaste värdet av rätt sort.

2024-01-25 11:49 UTC, jhsware approved these changes
Lets go with your suggestions!

2024-01-25 11:49 UTC, merged