Read current site without using RegEx
KTH/kpm pull request #227
Opened 2024-04-24 08:12 UTC by exacs

This PR changes the way kpm guesses which is the current "site" (external, student-web or intranet).

Instead of looking at the URL, it looks if a given class is present in the header.

2024-04-24 09:41 UTC, kaj commented
How about canvas and other apps that don't (yet) have the new kthstyle header?  I guess they will just be "none of the above", and that is probably fine?

(I just want that to be a concious decision, rather than just happening)

2024-04-25 07:07 UTC, exacs commented
@kaj Yes, Canvas and sites without any of the headers will be "none". All links will be "default" (blue text, transparent background), none of them marked.

2024-05-21 08:48 UTC, jhsware requested changes
I have some minor questions about the code. See comments.

2024-05-21 08:48 UTC, jhsware commented on kpm/kpm-frontend/src/components/entrances.tsx
> +  );
Do we have a custom element called "kth-header" or is this query selector a typo?

2024-05-21 08:48 UTC, jhsware commented on kpm/kpm-frontend/src/components/entrances.tsx
> +  const SITES = ["external", "intra", "student"] as const;
The site names don't match the classnames in the variable links. Considering the check classList.contains(site) this feels strange that they are so close but still not the same. If it is intentional, perhaps one could add a comment.

2024-05-21 08:48 UTC, jhsware commented on kpm/kpm-frontend/src/components/entrances.tsx
> +  );
notLoggedIn.js:L52 indicates typo.

2024-05-21 08:48 UTC, jhsware commented on kpm/kpm-backend/src/widget.js/notLoggedIn.js
> +  let currentLabel = currentItem?.label[lang] ?? links[0].label[lang];
Should we have a fallback?

2024-05-22 07:59 UTC, jhsware commented on kpm/kpm-frontend/src/components/entrances.tsx
> +function getCurrentSite(): keyof typeof labels | undefined {
Snyggt!

2024-05-22 12:21 UTC, jhsware approved these changes
LGTM

NOTE: I haven't test run the code.

2024-05-23 08:19 UTC, merged