Fix/accessible mobile menu
KTH/kpm pull request #229
Opened 2024-05-31 09:15 UTC by exacs

2024-06-10 08:43 UTC, jhsware commented on kpm/kpm-frontend/src/Menu.tsx
> +            </div>
Since we are moving the button out of the list (which feels reasonable), perhaps we should use \<header\> for this container instead of a generic div to emphasize the relationship with the list.

2024-06-10 08:59 UTC, jhsware requested changes
In general I think this is a great improvement. I have tested the interactions in the browser and they work as expected.

I have added a suggestion and a comment. Neither require any changes to approve this PR so once you have decided how you feel about the comments you can merge this without further review. Marking this with "request changes" is only so you don't miss the comments :)

2024-06-10 08:59 UTC, jhsware commented on kpm/kpm-frontend/src/Menu.scss
> +    display: none;
If we use `visibility: hidden` instead of `display: none`, we provide an opportunity to add a subtle animation when opening the menu:
```
visibility: hidden;
opacity: 0;
transition: opacity .3s;
```
and the corresponding:
```
visibility: visible;
opacity: 1;
```
on active.

The benefit of hiding the ul from layout calculations with `display: none` is not very high in this case.

2024-06-11 08:01 UTC, exacs commented on kpm/kpm-frontend/src/Menu.tsx
> +            </div>
I disagree with the use of `<header>` in this case for those reasons:

1. Landmarks (like `header`, `nav`, `main`, `footer`, etc.) does not give any semantic meaning when used inside another landmark (in this case it would be `header` inside `nav`). So, it is equivalent as `div`
2. Landmarks should be used to mark **important areas in a page**. Screen readers can show a list of all landmarks in a page, and showing too many of them it is actually bad.

To mark the relationship of the button and the list, in this case, it is better to use [aria-controls](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls)

2024-06-11 08:33 UTC, exacs commented on kpm/kpm-frontend/src/Menu.scss
> +    display: none;
That can work! Btw, check these new CSS things that are interesting regarding animating `display`:

- [`transition-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-behavior)
- [`@starting-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style)

Those are available in Chrome and Safari already and now in Firefox Nightly!

You can read [a better explanation in this article](https://nerdy.dev/using-starting-style-and-transition-behavior-for-enter-and-exit-stage-effects)

2024-06-12 07:47 UTC, exacs commented
I will merge this PR even when the "KPM ref" pipeline did not succeed. It seems that the security check is failing due to outdated dependencies. Will fix dependencies in a different branch or main

2024-06-12 07:47 UTC, merged

2024-06-12 09:34 UTC, jhsware commented on kpm/kpm-frontend/src/Menu.tsx
> +            </div>
Excellent!