Add username to menu
KTH/kpm pull request #4
Opened 2020-11-10 07:13 UTC by miyamoto-san

2020-11-10 07:43 UTC, kaj requested changes
Please either introduce a format checker / linter in a separate PR or just revert the formatting changes in this PR.  This way it is impossible to see the actual code changes that adds support for login.

2020-11-10 08:16 UTC, kaj reviewed
Looks like a reasonable first step.  I have some issues which needs to be adressed to get it running in stage.

I also think the actual login should not be handled in the request for `kpm.js` (which I think should be cacheable) but in a separate request for the content of the menu bar.  But having it _somewhere_ is a reasonable first step.

2020-11-10 08:16 UTC, kaj commented on app.js
> +  }
Why validate before parsing?  We still needs to handle an exception if we get a valid xml document without the expected fields.

2020-11-10 08:16 UTC, kaj commented on app.js
> +  const serviceUrl = "http://localdev.kth.se/kpm/kpm.js";
This should be `${aseUrl}/kpm.js`.

2020-11-10 08:16 UTC, kaj commented on app.js
> +  );
The login houst needs to come from the environment.

2020-11-10 08:16 UTC, kaj commented on app.js
> +      passphrase: "lolo",
We can't put the cert in the docker image, so I guess we need to get it through then environment and not from files.

2020-11-10 08:19 UTC, kaj commented on app.js
> +  );
I guess / hope it is enough to have one environment variable with the host name and build both `loginUrl` and `serviceValidateUrl` from that.  :-)

2020-11-10 08:20 UTC, miyamoto-san commented on app.js
> +  }
Yes, this is what I wanted to discuss!

2020-11-10 08:40 UTC, exacs commented on app.js
> +      passphrase: "lolo",
These files are only needed when running the app locally. Remember that in stage/prod, app is behind a reverse proxy that handles the HTTPS stuff.

If that is the case, I'd say we might need two "start" files or something

2020-11-11 11:14 UTC, kaj commented
Requests that has a `ticket` query parameter should always get a redirect.  But that requires some kind of session handling, so maybe it's for the next PR.

2020-11-11 11:20 UTC, kaj requested changes

2020-11-11 11:20 UTC, kaj commented on src/server.js
> +    const info = require("./buildinfo.js");
I think this needs to be `"../buildinfo.js"`, now that this function is moved into the `src` directory.

2020-11-11 13:14 UTC, merged