Make my-teaching-api return roles per course.
KTH/kpm pull request #43
Opened 2022-10-18 15:11 UTC by kaj

Not ready to merge yet, see review comments.

2022-10-18 15:17 UTC, kaj reviewed
I have some questions ...

2022-10-18 15:17 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +// assert(typeof CLIENT_SECRET === "string" && CLIENT_SECRET, "Missing CLIENT_SECRET for OpenID auth");
I think these asserts should be moved to `index.ts`, but then the above variable declarations also needs to be moved.  Without these asserts, the type of `proces.env.FOO` is `string | undefined`.  That's why i temporarily added `|| "wtf"` above to make sure they are strings and keep the type system happy.

2022-10-18 15:17 UTC, kaj commented on apis/my-teaching-api/src/api.ts
>  }
I don't think the description or kthid of an UG group are relevant to us, so even if they exists in the data, I see no reason for them to exist here (and keeping them makes mocking more verbose).

2022-10-18 15:17 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +      return res.status(statusCode || 500).send("error");
This is just to always send something, since I moved the rest of this function into an else to make sure that `json` is actually defined there.

2022-10-18 15:17 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +export function teachingResult(data: TUgGroup[]): { [index: string]: Array<Role> } {
I make the mapping from ug rest answer to our answer a separate function just so it can be tested.

2022-10-19 06:38 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +// assert(typeof CLIENT_SECRET === "string" && CLIENT_SECRET, "Missing CLIENT_SECRET for OpenID auth");
I suggest adding [@kth/reqvars](https://www.npmjs.com/package/@kth/reqvars) and removing the asserts entirely.

2022-10-19 06:47 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +      return res.status(statusCode || 500).send("error");
Perhaps we could change this to:
`
return res.status(statusCode || 500).send({ "error": "No valid JSON returned from UG REST API." });
`

2022-10-19 06:49 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +  return courses
Minor: we use semicolon terminated lines. Perhaps run prettier on the PR.

2022-10-19 06:52 UTC, jhsware requested changes
I think we should fix the asserts, either move them or implement @kth/reqvars and remove them. Also implement the same solution for my-studies-api, my-canvas-rooms for consistency.

2022-10-19 06:52 UTC, jhsware commented
I will fix the broken kpm-test.

2022-10-19 07:01 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +// assert(typeof CLIENT_SECRET === "string" && CLIENT_SECRET, "Missing CLIENT_SECRET for OpenID auth");
Reqvars seems to only check, not parse (or even get) the values?  The asserts here is mainly changing the type of those variables from `string | undefined` (or even `any`?) to `string`.

2022-10-19 07:04 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +      return res.status(statusCode || 500).send("error");
Yes.  Perhaps even changing the inner `if` to just log and send a known error?  Or even just to raise an exception if we check for that somewhere?

2022-10-19 07:22 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +  return courses
Prettier done (but I guess we should add a check to ci as well).

2022-10-19 07:51 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +// assert(typeof CLIENT_SECRET === "string" && CLIENT_SECRET, "Missing CLIENT_SECRET for OpenID auth");
Since all env-vars are strings the reqvars check will be equivalent to the assert so nothing lost. Also, the main use case is to answer the question "Why won't my app start?" when you check out the project for the first time.

2022-10-19 07:55 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +      return res.status(statusCode || 500).send("error");
Going forward we probably want to throw errors so we use the main error handler (hooked up in index.ts) so we can enforce consistent error reporting. Perhaps we should mob-program error handling later this week and let this be a temporary fix.

2022-10-19 07:56 UTC, jhsware commented on apis/my-teaching-api/src/api.ts
> +  return courses
We're going to hate that check though... unless this was a traumatic experience I think we should leave it as is for now.

2022-10-19 08:20 UTC, kaj commented on apis/my-teaching-api/src/api.ts
> +// assert(typeof CLIENT_SECRET === "string" && CLIENT_SECRET, "Missing CLIENT_SECRET for OpenID auth");
For the "why won't it start", reqvars is as good as this.  But for the types, I don't think reqvars (in index.ts) can tell the usage here that those specific environment variables are defined.  Note that just commenting out the checks made type checking fail in api.ts, so I had to add those temorary `|| "wtf"` parts.

2022-10-20 08:24 UTC, jhsware commented
@kaj the CD/CI-pipeline is fixed in main so you can rebase to get your tests to pass.

2022-10-20 12:38 UTC, jhsware approved these changes

2022-10-20 12:41 UTC, merged